FROM merged-video-ai-router:v2

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
ENV YOLO_CONFIG_DIR=/tmp
ENV MPLCONFIGDIR=/tmp/matplotlib

WORKDIR /workspace

# Install only application-level system dependencies inside the image.
# Nothing is installed on Windows.


# COPY requirements.deepstream.txt /workspace/requirements.txt

# RUN python3 -m pip install \
#     --no-cache-dir \
#     -r /workspace/requirements.txt

COPY . /workspace

# RUN python3 -m pip install \
#     --no-deps \
#     torch==2.4.1 \
#     torchvision==0.19.1 \
#     torchaudio==2.4.1 \
#     --index-url https://download.pytorch.org/whl/cu124 \
#     --proxy http://host.docker.internal:10808
# RUN pip install --no-cache-dir --no-deps ultralytics
RUN python3 -m pip install requests
RUN python3 -m pip uninstall -y transformers

RUN python3 -m pip install --no-cache-dir \
    "transformers==4.51.3"

RUN  pip install --no-cache-dir "tensorrt-cu12>=7.0.0,!=10.2.0"
RUN mkdir -p \
    /workspace/data \
    /workspace/saved_media \
    /workspace/models

EXPOSE 8000

CMD ["python3", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
