name: crnn_image2text
config_type: model
id2label:
  0: ''
  1: آ
  2: ا
  3: ب
  4: پ
  5: ت
  6: ث
  7: ج
  8: چ
  9: ه
  10: خ
  11: د
  12: ذ
  13: ر
  14: ز
  15: ژ
  16: س
  17: ش
  18: ص
  19: ض
  20: ط
  21: ظ
  22: ع
  23: غ
  24: ف
  25: ق
  26: ک
  27: گ
  28: ل
  29: م
  30: ن
  31: و
  32: ه
  33: ی
  34: ' '
  35: '۱'
  36: '۲'
  37: '۳'
  38: '۴'
  39: '۵'
  40: '۶'
  41: '۷'
  42: '۸'
  43: '۹'
  44: '۰'
blank_id: 0
n_channels: 1
image_height: 32
image_width: 128
map2seq_in_dim: 1024
map2seq_out_dim: 96
rnn_dim: 256
reverse_output_digits: true
