from __future__ import annotations

from typing import Dict


TABLE_VERBOSE_NAMES: Dict[str, str] = {
    "work_shifts": "شیفت‌های کاری",
    "detection_logs": "لاگ‌های تشخیص",
    "personnel": "پرسنل",
    "personnel_images": "تصاویر پرسنل",
    "users": "کاربران",
    "buildings": "ساختمان‌ها",
    "sections": "بخش‌ها",
    "general_settings": "تنظیمات عمومی",
    "cameras": "دوربین‌ها",
    "rooms": "اتاق‌ها",
    "personnel_requests": "درخواست‌های پرسنل",
    "holidays": "تعطیلات",
    "personnel_room_access": "تخصیص پرسنل به اتاق‌ها",
    "model_conversion_jobs": "وظایف خروجی مدل",
    "car_plates": "پلاک‌های خودرو",
    "plate_logs": "لاگ‌های تشخیص پلاک",
    "fire_smoke_logs": "لاگ‌های تشخیص حریق و دود",
    "fire_logs": "لاگ‌های حریق",
    "import_progress": "پیشرفت ورود اطلاعات",
    "plate_general_settings": "تنظیمات عمومی پلاک",
    "plate_camera_settings": "تنظیمات پلاک دوربین",
    "model_general_settings": "تنظیمات عمومی مدل",
    "human_logs": "لاگ‌های تردد افراد",
    "face_quality_settings": "تنظیمات کیفیت چهره",
    "face_embeddings": "بردارهای ویژگی چهره",
    "revoked_tokens": "توکن‌های باطل‌شده",
    "personnel_images": "تصاویر پرسنل",
    "detection_room_matches": "تطبیق اتاق‌های تشخیص",
    "personnel_room_access": "دسترسی اتاق پرسنل",
}

FIELD_VERBOSE_NAMES: Dict[str, Dict[str, str]] = {
    "work_shifts": {
        "id": "شناسه",
        "shift_name": "نام شیفت",
        "shift_type": "نوع شیفت",
        "start_time": "ساعت شروع",
        "end_time": "ساعت پایان",
        "timezone_name": "منطقه زمانی",
        "max_overtime_hours": "حداکثر ساعات اضافه‌کاری",
        "max_minutes_delay": "حداکثر دقیقه تأخیر مجاز",
        "max_minutes_early": "حداکثر دقیقه خروج زودهنگام مجاز",
        "works_saturday": "شنبه روز کاری است",
        "works_sunday": "یکشنبه روز کاری است",
        "works_monday": "دوشنبه روز کاری است",
        "works_tuesday": "سه‌شنبه روز کاری است",
        "works_wednesday": "چهارشنبه روز کاری است",
        "works_thursday": "پنجشنبه روز کاری است",
        "works_friday": "جمعه روز کاری است",
        "created_at_utc": "زمان ایجاد",
        "updated_at_utc": "زمان آخرین به‌روزرسانی",
    },
    "detection_logs": {
        "id": "شناسه",
        "source_system": "سیستم مبدأ",
        "source_event_key": "کلید رویداد مبدأ",
        "source_human_log_id": "شناسه لاگ انسانی مبدأ",
        "personnel_id": "شناسه پرسنل",
        "person": "شناسه شخص تشخیص‌داده‌شده",
        "confidence": "میزان اطمینان",
        "detection_time": "زمان تشخیص",
        "ref_img_id": "شناسه تصویر مرجع",
        "room_id": "شناسه اتاق",
        "camera_id": "شناسه دوربین",
        "access_granted": "دسترسی مجاز است",
        "counts_for_attendance": "در محاسبات حضور و غیاب لحاظ شود",
        "log_type": "نوع لاگ",
        "import_source_parts": "جزئیات منبع واردسازی",
        "face_image": "تصویر چهره",
        "body_image": "تصویر بدن",
        "snapshot_image": "تصویر لحظه‌ای",
        "video": "فیلم",
        "face_video_or_unknown_faces": "فیلم چهره یا چهره‌های ناشناس",
        "created_by": "ایجادکننده",
        "updated_by": "آخرین ویرایش‌کننده",
        "created_at_utc": "زمان ایجاد",
        "updated_at_utc": "زمان آخرین به‌روزرسانی",
    },
    "personnel": {
        "id": "شناسه",
        "fname": "نام",
        "lname": "نام خانوادگی",
        "national_code": "کد ملی",
        "employee_type": "نوع استخدام",
        "employee_type_id": "شناسه نوع استخدام",
        "degree": "مدرک تحصیلی",
        "department_id": "شناسه بخش",
        "shift_id": "شناسه شیفت کاری",
        "last_seen": "آخرین مشاهده",
        "created_at_utc": "زمان ایجاد",
        "updated_at_utc": "زمان آخرین به‌روزرسانی",
    },
    "personnel_images": {
        "id": "شناسه",
        "personnel_id": "شناسه پرسنل",
        "storage_key": "آدرس تصویر",
        "description": "توضیحات تصویر",
        "is_primary": "تصویر اصلی است",
        "uploaded_at_utc": "زمان بارگذاری",
        "embedding_id": "شناسه بردار ویژگی",
    },
    "users": {
        "id": "شناسه",
        "username": "نام کاربری",
        "password_hash": "گذرواژه هش‌شده",
        "role": "نقش کاربری",
        "is_active": "فعال است",
        "email": "ایمیل",
        "full_name": "نام و نام خانوادگی",
        "last_login_utc": "زمان آخرین ورود",
        "login_attempts": "تعداد تلاش‌های ورود",
        "locked_until_utc": "حساب تا این زمان قفل است",
        "created_at_utc": "زمان ایجاد",
    },
    "buildings": {
        "id": "شناسه",
        "name": "نام ساختمان",
        "address": "آدرس ساختمان",
        "description": "توضیحات",
        "created_at_utc": "زمان ایجاد",
        "updated_at_utc": "زمان آخرین به‌روزرسانی",
    },
    "sections": {
        "id": "شناسه",
        "building_id": "شناسه ساختمان",
        "name": "نام بخش",
        "description": "توضیحات",
        "created_at_utc": "زمان ایجاد",
        "updated_at_utc": "زمان آخرین به‌روزرسانی",
    },
    "general_settings": {
        "id": "شناسه",
        "enable_processing": "پردازش تشخیص چهره",
        "process_fire": "پردازش تشخیص حریق",
        "process_plate": "پردازش تشخیص پلاک خودرو",
        "counts_for_attendance": "ثبت لاگ‌ها در محاسبات حضور و غیاب",
        "margin_level": "سطح حاشیه تشخیص",
        "draw_box": "ترسیم کادر تشخیص",
        "draw_face": "ترسیم چهره",
        "draw_skeleton": "ترسیم اسکلت بدن",
        "draw_zones": "ترسیم نواحی",
        "face_rec_score": "آستانه امتیاز شناسایی چهره",
        "face_det_score": "آستانه امتیاز تشخیص چهره",
        "human_det_score": "آستانه امتیاز تشخیص انسان",
        "confirmation_threshold": "آستانه تأیید نهایی",
        "force": "اعمال اجباری تنظیمات عمومی",
        "operational_json": "تنظیمات عملیاتی",
        "created_by": "ایجادکننده",
        "updated_by": "آخرین ویرایش‌کننده",
        "created_at_utc": "زمان ایجاد",
        "updated_at_utc": "زمان آخرین به‌روزرسانی",
    },
    "cameras": {
        "camera_id": "شناسه دوربین",
        "name": "نام دوربین",
        "enabled": "فعال است",
        "tasks_json": "وظایف محول‌شده",
        "source_uri": "آدرس منبع",
        "frame_width": "عرض فریم",
        "frame_height": "ارتفاع فریم",
        "section_id": "شناسه بخش",
        "metadata_json": "فراداده",
        "created_at_utc": "زمان ایجاد",
        "updated_at_utc": "زمان آخرین به‌روزرسانی",
    },
    "rooms": {
        "id": "شناسه",
        "section_id": "شناسه بخش",
        "name": "نام اتاق",
        "description": "توضیحات",
        "polygon_json": "نقاط محدوده چندضلعی",
        "created_at_utc": "زمان ایجاد",
        "updated_at_utc": "زمان آخرین به‌روزرسانی",
    },
    "personnel_requests": {
        "id": "شناسه",
        "personnel_id": "شناسه پرسنل",
        "request_type": "نوع درخواست",
        "duration_type": "نوع مدت درخواست",
        "duration_days": "تعداد روز محاسبه‌شده",
        "duration_minutes": "دقایق محاسبه‌شده",
        "status": "وضعیت درخواست",
        "start_date": "تاریخ شروع",
        "end_date": "تاریخ پایان",
        "start_time": "ساعت شروع",
        "end_time": "ساعت پایان",
        "reason": "توضیحات درخواست",
        "admin_notes": "یادداشت مدیر",
        "rejection_reason": "دلیل رد درخواست",
        "approved_by": "تأییدکننده",
        "reviewed_by": "بررسی‌کننده",
        "reviewed_at": "زمان بررسی",
        "created_at_utc": "زمان ایجاد",
        "updated_at_utc": "زمان آخرین به‌روزرسانی",
    },
    "holidays": {
        "id": "شناسه",
        "name": "عنوان تعطیلی",
        "date_value": "تاریخ تعطیلی",
        "description": "توضیحات",
        "holiday_type": "نوع تعطیلی",
        "every_year": "تکرار سالانه",
        "is_active": "فعال است",
        "created_at_utc": "زمان ایجاد",
        "updated_at_utc": "زمان آخرین به‌روزرسانی",
    },
    "car_plates": {
        "id": "شناسه",
        "left_digits": "دو رقم سمت چپ پلاک",
        "plate_alphabet": "حرف فارسی پلاک",
        "right_digits": "سه رقم سمت راست پلاک",
        "iran_code": "کد ایران پلاک",
        "plate_format": "قالب پلاک",
        "usage_type": "نوع کاربری خودرو",
        "vehicle_type": "نوع وسیله نقلیه",
        "owner_name": "نام مالک",
        "owner_phone": "شماره تلفن مالک",
        "color": "رنگ خودرو",
        "brand": "برند خودرو",
        "model": "مدل خودرو",
        "manufacture_year": "سال ساخت",
        "description": "توضیحات",
        "is_active": "فعال است",
        "deleted_at_utc": "زمان حذف",
        "created_at_utc": "زمان ایجاد",
        "updated_at_utc": "زمان آخرین به‌روزرسانی",
        "created_by": "ایجادکننده",
        "updated_by": "آخرین ویرایش‌کننده",
    },
    "plate_logs": {
        "id": "شناسه",
        "source_type": "نوع منبع ثبت",
        "source_uri": "نشانی منبع دوربین",
        "static_video_id": "شناسه ویدیوی ایستا",
        "created_by_user_id": "کاربر ثبت‌کننده",
        "updated_by_user_id": "آخرین کاربر ویرایش‌کننده",
        "plate_id": "شناسه پلاک ثبت‌شده",
        "plate_number": "شماره پلاک",
        "raw_plate_text": "متن خام تشخیص پلاک",
        "confidence": "میزان اطمینان تشخیص",
        "detection_time": "زمان تشخیص",
        "snapshot_key": "کلید تصویر لحظه‌ای",
        "video_key": "کلید ویدیوی تشخیص",
        "notes": "یادداشت",
        "created_at": "زمان ایجاد",
        "updated_at": "زمان آخرین به‌روزرسانی",
    },
    "fire_smoke_logs": {
        "id": "شناسه",
        "camera": "دوربین",
        "time": "زمان تشخیص",
        "incident_id": "شناسه رویداد",
        "severity": "شدت خطر",
        "fire_count": "تعداد حریق",
        "smoke_count": "تعداد دود",
        "fire_confidence": "میزان اطمینان حریق",
        "smoke_confidence": "میزان اطمینان دود",
        "window_seconds": "پنجره زمانی",
        "snapshot_url": "آدرس تصویر لحظه‌ای",
        "details_json": "جزئیات",
    },
    "import_progress": {
        "id": "شناسه",
        "import_type": "نوع ورود اطلاعات",
        "source_filename": "نام فایل مبدأ",
        "total_rows": "تعداد کل ردیف‌ها",
        "imported_rows": "ردیف‌های واردشده",
        "skipped_rows": "ردیف‌های ردشده",
        "failed_rows": "ردیف‌های ناموفق",
        "status": "وضعیت",
        "error_message": "پیام خطا",
        "created_by": "ایجادکننده",
        "created_at_utc": "زمان ایجاد",
        "updated_at_utc": "زمان آخرین به‌روزرسانی",
    },
    "face_embeddings": {
        "id": "شناسه",
        "person": "شخص",
        "ref_img_id": "شناسه تصویر مرجع",
        "embedding": "بردار ویژگی",
        "dimension": "بعد",
        "created_at_utc": "زمان ایجاد",
    },
    "human_logs": {
        "id": "شناسه",
        "session_id": "شناسه جلسه",
        "camera": "دوربین",
        "track_id": "شناسه ردیابی",
        "name": "نام",
        "first_seen": "اولین مشاهده",
        "last_seen": "آخرین مشاهده",
        "recognition_score": "امتیاز تشخیص",
        "ref_img_id": "شناسه تصویر مرجع",
        "snapshot_url": "آدرس تصویر لحظه‌ای",
        "video_url": "آدرس فیلم",
        "face_video_url": "آدرس فیلم چهره",
        "snapshot_quality": "کیفیت تصویر لحظه‌ای",
        "best_face_quality": "بهترین کیفیت چهره",
        "full_frame_video_frames": "فریم‌های فیلم کامل",
        "accepted_face_frames": "فریم‌های چهره پذیرفته‌شده",
        "personnel_id": "شناسه پرسنل",
        "counts_for_attendance": "در محاسبات حضور لحاظ شود",
    },
    "personnel_room_access": {
        "id": "شناسه",
        "personnel_id": "شناسه پرسنل",
        "room_id": "شناسه اتاق",
        "granted_at_utc": "زمان تخصیص",
        "granted_by": "تخصیص‌دهنده",
    },
    "plate_general_settings": {
        "id": "شناسه",
        "vehicle_confidence": "آستانه اطمینان خودرو",
        "plate_confidence": "آستانه اطمینان پلاک",
        "ocr_confidence": "آستانه اطمینان OCR",
        "min_vehicle_width_pixels": "حداقل عرض خودرو",
        "min_vehicle_height_pixels": "حداقل ارتفاع خودرو",
        "min_vehicle_area_ratio": "حداقل نسبت مساحت خودرو",
        "vehicle_crop_padding_ratio": "نسبت حاشیه برش خودرو",
        "updated_at_utc": "زمان آخرین به‌روزرسانی",
    },
    "model_general_settings": {
        "id": "شناسه",
        "fire_smoke_model": "مدل تشخیص حریق و دود",
        "vehicle_detector_model": "مدل تشخیص خودرو",
        "plate_detector_model": "مدل تشخیص پلاک",
        "preferred_format": "فرمت ترجیحی",
        "allow_onnx_fallback": "مجاز بودن ONNX",
        "allow_pt_fallback": "مجاز بودن PT",
        "export_imgsz": "اندازه تصویر خروجی",
        "export_batch_size": "اندازه دسته خروجی",
        "export_workspace_gb": "فضای کاری خروجی",
        "export_half": "نیمه‌دقت",
        "export_dynamic": "پویا",
        "export_timeout_seconds": "مهلت زمانی خروجی",
        "updated_at_utc": "زمان آخرین به‌روزرسانی",
    },
}


def get_table_verbose_name(table_name: str) -> str:
    return TABLE_VERBOSE_NAMES.get(table_name, table_name)


def get_field_verbose_name(table_name: str, field_name: str) -> str:
    fields = FIELD_VERBOSE_NAMES.get(table_name, {})
    return fields.get(field_name, field_name)
